baseURL = "https://honeysens.org/"
languageCode = "en-us"
title = "HoneySens"
themesDir = "themes"
theme = "honeysens-whisper"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Releases"
    url = "/releases/"
    weight = 3

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/HoneySens/honeysens"
    weight = 4

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Learn more'
  homepage_image = '/images/architecture.png'
  mainSections = ["docs", "releases", "misc"]

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "An open platform to deploy and manage honeypots on a variety of hardware and software architectures"
    meta_og_title = "HoneySens"
    meta_og_type = "website"
    meta_og_url = "https://honeysens.org/"
    meta_og_image = "https://honeysens.org/images/logo.svg"
    meta_og_description = "An open platform to deploy and manage honeypots on a variety of hardware and software architectures"
    #meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

  [params.logo]
      mobile = "/images/logo.svg"
      standard  = "/images/logo.svg"
